### ISSUE TITLE
bit_vector.py question

### ISSUE THREAD

**Issue by xxy103** [jyesselm/dreem#4]
Hi, 

May I ask a question related to the bit_vector.py algorithm?
In the bit_vector.py code that used to count the nucleotide mutation profile, why only the CIGAR field was being parsed but not the MD TAG field? Does not exclude some potential mutational profile? 

Best,

**Comment by jyesselm** [comment]
Hi could you give an example where it would miss a mutation? I thought most of that information as redundant.
